server:
  port: 8071

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

exchange:
  base-url: "http://localhost:48071"

resilience4j:
  retry:
    instances:
      exchange-service:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.trevizan.mithrilledger.exception.infrastructure.ExchangeServiceUnavailableException
  circuitbreaker:
    instances:
      exchange-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 1
        record-exceptions:
          - com.trevizan.mithrilledger.exception.infrastructure.ExchangeServiceUnavailableException
          - com.trevizan.mithrilledger.exception.infrastructure.ExchangeInvalidResponseException
